### ISSUE TITLE
`isLink` returns true for incorrect entities.

### ISSUE THREAD

**Issue by danbedford56** [HPouyanmehr/contenido#12]
The `isLink` function ([here](https://github.com/HPouyanmehr/contenido/blob/main/packages/core/src/utilities/entity/isLink.ts)) returns true for custom entity types.

This is due to missing parenthesis within the entity type check shown below:
```
if (entityType === customLinkKey ? customLinkKey : 'LINK') return true;
```

Below are 2 tested solutions:
1 (Nicest IMO):
```
return entityType === (customLinkKey ?? 'LINK');
```

2.
```
if (entityType === (customLinkKey ?? 'LINK')) return true;
```

**Comment by HPouyanmehr** [comment]
Hey @danbedford56,

Thanks for reporting the issue. I've applied your solution (nicest one😁) and you can update to [v1.2.14](https://github.com/HPouyanmehr/contenido/releases/tag/v1.2.14).
