### ISSUE TITLE
Link entity key mismatched.

### ISSUE THREAD

**Issue by danbedford56** [HPouyanmehr/contenido#13]
First of all, apologies for missing this in my previous issue. I was using a custom link entity and didn't come across this.

In `isLink` the key used to check the entity type is in all caps (LINK). Whereas when adding a link using the `addLink` function, the key used is in lowercase (link) with no parameter available to pass a custom key.

**Comment by danbedford56** [comment]
Fix PR: #14

**Comment by HPouyanmehr** [comment]
Hey Dan, Thanks for reporting and for the PR. I really appreciate it.

I've merged and published your changes [(v1.2.15](https://github.com/HPouyanmehr/contenido/releases/tag/v1.2.15).)
